export const ERROR_CODES = {
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',

  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_BLOCKED: 'AUTH_ACCOUNT_BLOCKED',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID: 'AUTH_2FA_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_DUPLICATE_EMAIL: 'AUTH_DUPLICATE_EMAIL',
  AUTH_DUPLICATE_USERNAME: 'AUTH_DUPLICATE_USERNAME',
  AUTH_REGISTRATION_FAILED: 'AUTH_REGISTRATION_FAILED',

  // Admin
  ADMIN_UNAUTHORIZED: 'ADMIN_UNAUTHORIZED',
  ADMIN_LOCKED: 'ADMIN_LOCKED',
  ADMIN_LOGIN_FAILED: 'ADMIN_LOGIN_FAILED',
  ADMIN_VERIFY_FAILED: 'ADMIN_VERIFY_FAILED',
  ADMIN_BACKFILL_FAILED: 'ADMIN_BACKFILL_FAILED',
  ADMIN_CSRF_FAILED: 'ADMIN_CSRF_FAILED',

  // Post
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_CREATE_FAILED: 'POST_CREATE_FAILED',
  POST_UPDATE_FAILED: 'POST_UPDATE_FAILED',
  POST_DELETE_FAILED: 'POST_DELETE_FAILED',
  POST_FETCH_FAILED: 'POST_FETCH_FAILED',

  // Comment
  COMMENT_FETCH_FAILED: 'COMMENT_FETCH_FAILED',
  COMMENT_CREATE_FAILED: 'COMMENT_CREATE_FAILED',
  COMMENT_UPDATE_FAILED: 'COMMENT_UPDATE_FAILED',
  COMMENT_DELETE_FAILED: 'COMMENT_DELETE_FAILED',

  // Tool
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_FETCH_FAILED: 'TOOL_FETCH_FAILED',
  TOOL_CREATE_FAILED: 'TOOL_CREATE_FAILED',
  TOOL_UPDATE_FAILED: 'TOOL_UPDATE_FAILED',
  TOOL_DELETE_FAILED: 'TOOL_DELETE_FAILED',

  // Tutorial
  TUTORIAL_NOT_FOUND: 'TUTORIAL_NOT_FOUND',
  TUTORIAL_FETCH_FAILED: 'TUTORIAL_FETCH_FAILED',
  TUTORIAL_CREATE_FAILED: 'TUTORIAL_CREATE_FAILED',
  TUTORIAL_UPDATE_FAILED: 'TUTORIAL_UPDATE_FAILED',
  TUTORIAL_DELETE_FAILED: 'TUTORIAL_DELETE_FAILED',

  // Bot
  BOT_NOT_FOUND: 'BOT_NOT_FOUND',
  BOT_FETCH_FAILED: 'BOT_FETCH_FAILED',
  BOT_CREATE_FAILED: 'BOT_CREATE_FAILED',
  BOT_UPDATE_FAILED: 'BOT_UPDATE_FAILED',
  BOT_DELETE_FAILED: 'BOT_DELETE_FAILED',
  BOT_SUBMIT_FAILED: 'BOT_SUBMIT_FAILED',

  // Media
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MEDIA_DELETE_FAILED: 'MEDIA_DELETE_FAILED',
  MEDIA_FETCH_FAILED: 'MEDIA_FETCH_FAILED',

  // Video
  VIDEO_NOT_FOUND: 'VIDEO_NOT_FOUND',
  VIDEO_FETCH_FAILED: 'VIDEO_FETCH_FAILED',
  VIDEO_CREATE_FAILED: 'VIDEO_CREATE_FAILED',
  VIDEO_UPDATE_FAILED: 'VIDEO_UPDATE_FAILED',
  VIDEO_DELETE_FAILED: 'VIDEO_DELETE_FAILED',

  // Category
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_FETCH_FAILED: 'CATEGORY_FETCH_FAILED',
  CATEGORY_CREATE_FAILED: 'CATEGORY_CREATE_FAILED',
  CATEGORY_UPDATE_FAILED: 'CATEGORY_UPDATE_FAILED',
  CATEGORY_DELETE_FAILED: 'CATEGORY_DELETE_FAILED',

  // Tag
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TAG_FETCH_FAILED: 'TAG_FETCH_FAILED',
  TAG_CREATE_FAILED: 'TAG_CREATE_FAILED',
  TAG_UPDATE_FAILED: 'TAG_UPDATE_FAILED',
  TAG_DELETE_FAILED: 'TAG_DELETE_FAILED',

  // Folder
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
  FOLDER_FETCH_FAILED: 'FOLDER_FETCH_FAILED',
  FOLDER_CREATE_FAILED: 'FOLDER_CREATE_FAILED',
  FOLDER_UPDATE_FAILED: 'FOLDER_UPDATE_FAILED',
  FOLDER_DELETE_FAILED: 'FOLDER_DELETE_FAILED',

  // Contact
  CONTACT_SEND_FAILED: 'CONTACT_SEND_FAILED',
  CONTACT_VALIDATION_FAILED: 'CONTACT_VALIDATION_FAILED',

  // Newsletter
  NEWSLETTER_SUBSCRIBE_FAILED: 'NEWSLETTER_SUBSCRIBE_FAILED',

  // Encyclopedia
  ENCYCLOPEDIA_FETCH_FAILED: 'ENCYCLOPEDIA_FETCH_FAILED',
  ENCYCLOPEDIA_NOT_FOUND: 'ENCYCLOPEDIA_NOT_FOUND',
  ENCYCLOPEDIA_CREATE_FAILED: 'ENCYCLOPEDIA_CREATE_FAILED',
  ENCYCLOPEDIA_UPDATE_FAILED: 'ENCYCLOPEDIA_UPDATE_FAILED',
  ENCYCLOPEDIA_DELETE_FAILED: 'ENCYCLOPEDIA_DELETE_FAILED',
  ENCYCLOPEDIA_MIGRATE_FAILED: 'ENCYCLOPEDIA_MIGRATE_FAILED',

  // Prompt
  PROMPT_NOT_FOUND: 'PROMPT_NOT_FOUND',
  PROMPT_FETCH_FAILED: 'PROMPT_FETCH_FAILED',
  PROMPT_CREATE_FAILED: 'PROMPT_CREATE_FAILED',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_FETCH_FAILED: 'USER_FETCH_FAILED',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',

  // Analytics
  ANALYTICS_FETCH_FAILED: 'ANALYTICS_FETCH_FAILED',

  // SEO
  SEO_FETCH_FAILED: 'SEO_FETCH_FAILED',
  SEO_UPDATE_FAILED: 'SEO_UPDATE_FAILED',

  // File
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Settings
  SETTINGS_FETCH_FAILED: 'SETTINGS_FETCH_FAILED',
  SETTINGS_UPDATE_FAILED: 'SETTINGS_UPDATE_FAILED',

  // Backup
  BACKUP_NOT_FOUND: 'BACKUP_NOT_FOUND',
  BACKUP_DELETE_FAILED: 'BACKUP_DELETE_FAILED',

  // Cron Job
  CRON_FETCH_FAILED: 'CRON_FETCH_FAILED',
  CRON_CREATE_FAILED: 'CRON_CREATE_FAILED',
  CRON_UPDATE_FAILED: 'CRON_UPDATE_FAILED',
  CRON_NOT_FOUND: 'CRON_NOT_FOUND',
  CRON_DELETE_FAILED: 'CRON_DELETE_FAILED',

  // Notification
  NOTIFICATION_FETCH_FAILED: 'NOTIFICATION_FETCH_FAILED',
  NOTIFICATION_CREATE_FAILED: 'NOTIFICATION_CREATE_FAILED',
  NOTIFICATION_UPDATE_FAILED: 'NOTIFICATION_UPDATE_FAILED',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_DELETE_FAILED: 'NOTIFICATION_DELETE_FAILED',

  // Redirect
  REDIRECT_FETCH_FAILED: 'REDIRECT_FETCH_FAILED',
  REDIRECT_CREATE_FAILED: 'REDIRECT_CREATE_FAILED',
  REDIRECT_UPDATE_FAILED: 'REDIRECT_UPDATE_FAILED',
  REDIRECT_NOT_FOUND: 'REDIRECT_NOT_FOUND',
  REDIRECT_DELETE_FAILED: 'REDIRECT_DELETE_FAILED',

  // Task
  TASK_FETCH_FAILED: 'TASK_FETCH_FAILED',
  TASK_CREATE_FAILED: 'TASK_CREATE_FAILED',
  TASK_UPDATE_FAILED: 'TASK_UPDATE_FAILED',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_DELETE_FAILED: 'TASK_DELETE_FAILED',

  // Tracking / Analytics
  TRACKING_FETCH_FAILED: 'TRACKING_FETCH_FAILED',
  TRACKING_RECORD_FAILED: 'TRACKING_RECORD_FAILED',
  TRACKING_EXPORT_FAILED: 'TRACKING_EXPORT_FAILED',
  TRACKING_CLEANUP_FAILED: 'TRACKING_CLEANUP_FAILED',

  // Search
  SEARCH_FAILED: 'SEARCH_FAILED',

  // Email
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

  // Session
  SESSION_FETCH_FAILED: 'SESSION_FETCH_FAILED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_REVOKE_FAILED: 'SESSION_REVOKE_FAILED',

  // Job
  JOB_FETCH_FAILED: 'JOB_FETCH_FAILED',
  JOB_CREATE_FAILED: 'JOB_CREATE_FAILED',
  JOB_UPDATE_FAILED: 'JOB_UPDATE_FAILED',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_DELETE_FAILED: 'JOB_DELETE_FAILED',

  // Mystic
  MYSTIC_FETCH_FAILED: 'MYSTIC_FETCH_FAILED',
  MYSTIC_HISTORY_FAILED: 'MYSTIC_HISTORY_FAILED',

  // Conversion (gamification)
  CONVERSION_FETCH_FAILED: 'CONVERSION_FETCH_FAILED',
  CONVERSION_ACTION_FAILED: 'CONVERSION_ACTION_FAILED',

  // Prompt (additional)
  PROMPT_UPDATE_FAILED: 'PROMPT_UPDATE_FAILED',
  PROMPT_DELETE_FAILED: 'PROMPT_DELETE_FAILED',
  PROMPT_PURCHASE_FAILED: 'PROMPT_PURCHASE_FAILED',
  PROMPT_REVIEW_FAILED: 'PROMPT_REVIEW_FAILED',
  PROMPT_PARSE_FAILED: 'PROMPT_PARSE_FAILED',
  PROMPT_GENERATE_FAILED: 'PROMPT_GENERATE_FAILED',

  // User (additional)
  USER_DELETE_FAILED: 'USER_DELETE_FAILED',

  // CSRF
  CSRF_GENERATION_FAILED: 'CSRF_GENERATION_FAILED',

  // Payout
  PAYOUT_FETCH_FAILED: 'PAYOUT_FETCH_FAILED',
  PAYOUT_REQUEST_FAILED: 'PAYOUT_REQUEST_FAILED',

  // Subscription
  SUBSCRIPTION_FETCH_FAILED: 'SUBSCRIPTION_FETCH_FAILED',
  SUBSCRIPTION_FAILED: 'SUBSCRIPTION_FAILED',

  // Bot Comment
  BOT_COMMENT_FETCH_FAILED: 'BOT_COMMENT_FETCH_FAILED',
  BOT_COMMENT_CREATE_FAILED: 'BOT_COMMENT_CREATE_FAILED',

  // Seed
  SEED_FAILED: 'SEED_FAILED',

  // Health
  HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',

  // AI
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',

  // Telegram
  TELEGRAM_VERIFICATION_FAILED: 'TELEGRAM_VERIFICATION_FAILED',

  // Premium Request
  PREMIUM_REQUEST_FAILED: 'PREMIUM_REQUEST_FAILED',

  // Vibe Code
  VIBE_CODE_FETCH_FAILED: 'VIBE_CODE_FETCH_FAILED',
  VIBE_CODE_CREATE_FAILED: 'VIBE_CODE_CREATE_FAILED',
  VIBE_CODE_NOT_FOUND: 'VIBE_CODE_NOT_FOUND',

  // Product
  PRODUCT_FETCH_FAILED: 'PRODUCT_FETCH_FAILED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',

  // Service
  SERVICE_FETCH_FAILED: 'SERVICE_FETCH_FAILED',
  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',

  // Backup (additional)
  BACKUP_FETCH_FAILED: 'BACKUP_FETCH_FAILED',
  BACKUP_CREATE_FAILED: 'BACKUP_CREATE_FAILED',
  BACKUP_RESTORE_FAILED: 'BACKUP_RESTORE_FAILED',

  // Chat
  CHAT_FAILED: 'CHAT_FAILED',

  // Error Log
  ERROR_LOG_FETCH_FAILED: 'ERROR_LOG_FETCH_FAILED',
  ERROR_LOG_CREATE_FAILED: 'ERROR_LOG_CREATE_FAILED',
  ERROR_LOG_DELETE_FAILED: 'ERROR_LOG_DELETE_FAILED',

  // Telegram (additional)
  TELEGRAM_POST_FAILED: 'TELEGRAM_POST_FAILED',

  // YouTube
  YOUTUBE_FETCH_FAILED: 'YOUTUBE_FETCH_FAILED',

  // Bot (additional)
  BOT_LIKE_FAILED: 'BOT_LIKE_FAILED',
  BOT_PURCHASE_CHECK_FAILED: 'BOT_PURCHASE_CHECK_FAILED',

  // Profile
  PROFILE_FETCH_FAILED: 'PROFILE_FETCH_FAILED',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',

  // Prompt Builder
  PROMPT_BUILDER_FAILED: 'PROMPT_BUILDER_FAILED',

  // Media (additional)
  MEDIA_FOLDER_FAILED: 'MEDIA_FOLDER_FAILED',

  // Product (additional)
  PRODUCT_CREATE_FAILED: 'PRODUCT_CREATE_FAILED',
  PRODUCT_UPDATE_FAILED: 'PRODUCT_UPDATE_FAILED',
  PRODUCT_DELETE_FAILED: 'PRODUCT_DELETE_FAILED',

  // Service (additional)
  SERVICE_CREATE_FAILED: 'SERVICE_CREATE_FAILED',
  SERVICE_UPDATE_FAILED: 'SERVICE_UPDATE_FAILED',
  SERVICE_DELETE_FAILED: 'SERVICE_DELETE_FAILED',

  // SEO (additional)
  SEO_CRON_FAILED: 'SEO_CRON_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
