// Types for the file-based course system (Georgian "AI for Beginners").
// Content is generated by scripts/ingest-ai-for-beginners.ts into
// src/data/courses/<courseSlug>/ and read at request time by the reader route.

export interface CourseAttribution {
    source: string;   // e.g. "Microsoft AI for Beginners"
    license: string;  // e.g. "MIT"
    url: string;      // upstream repo URL
    sourcePath?: string; // original file path inside the upstream tree (per lesson)
}

export interface CourseHeading {
    id: string;    // slugged with the same algorithm as TableOfContents.tsx
    text: string;
    level: number; // 1..3
}

export type NotebookFramework = 'pytorch' | 'tensorflow' | 'generic';
export type LessonKind = 'markdown' | 'notebook';

// --- Manifest (drives sidebar + library, small enough to import client-side) ---

export interface CourseLessonRef {
    slug: string;          // full path slug, e.g. "symbolic/animals"
    segments: string[];    // ["symbolic", "animals"]
    title: string;
    lessonNumber: number | null;
    kind: LessonKind;
    framework?: NotebookFramework;
    readingMinutes?: number;
}

export interface CourseModule {
    id: string;            // upstream folder, e.g. "2-Symbolic"
    order: number;         // numeric prefix, e.g. 2
    slug: string;          // "symbolic"
    title: string;
    description?: string;
    icon?: string;         // Tabler icon name (resolved by ModuleIcon.tsx) — never an emoji
    lessons: CourseLessonRef[];
}

export interface CourseManifest {
    slug: string;          // "ai-for-beginners"
    title: string;
    language: 'ka';
    attribution: CourseAttribution;
    modules: CourseModule[];
    totals: { modules: number; lessons: number; notebooks: number };
    generatedAt: string;
}

// --- Notebook cell model (parsed at ingest time, never at request time) ---

export interface NotebookTextOutput {
    kind: 'text';
    text: string;
    stream?: string; // "stdout" | "stderr" | undefined
}
export interface NotebookImageOutput {
    kind: 'image';
    src: string; // public path, e.g. "/courses/ai-for-beginners/_nb/<hash>.png"
}
export type NotebookOutput = NotebookTextOutput | NotebookImageOutput;

export interface NotebookMarkdownCell {
    type: 'markdown';
    source: string;
}
export interface NotebookCodeCell {
    type: 'code';
    language: string; // "python"
    source: string;
    executionCount: number | null;
    outputs: NotebookOutput[];
}
export type NotebookCell = NotebookMarkdownCell | NotebookCodeCell;

// --- Lesson payloads (one JSON file per lesson) ---

export interface CourseLessonNav {
    slug: string;
    title: string;
}

interface CourseLessonBase {
    courseSlug: string;
    slug: string;
    segments: string[];
    title: string;
    module: { id: string; slug: string; title: string; icon?: string };
    lessonNumber: number | null;
    orderInModule: number; // deterministic sort key, used to rebuild the manifest from disk
    attribution: CourseAttribution;
    prev: CourseLessonNav | null;
    next: CourseLessonNav | null;
}

export interface CourseMarkdownLesson extends CourseLessonBase {
    kind: 'markdown';
    markdown: string;
    headings: CourseHeading[];
    readingMinutes: number;
}

export interface CourseNotebookLesson extends CourseLessonBase {
    kind: 'notebook';
    framework: NotebookFramework;
    cells: NotebookCell[];
    sourceNotebookUrl?: string; // upstream .ipynb URL (download / Colab)
}

export type CourseLesson = CourseMarkdownLesson | CourseNotebookLesson;
